# -*- coding: utf-8 -*-
"""Portfolio content, from the client inventory (memory notes, Drive client folders, repos, session history).
   Facts only: no prices, no staff names, no results or metrics, nothing under NDA. Status is stated honestly:
   'clients' have delivered work or work under way."""

# services: key -> label (the cover marquee, the directory filters and the detail chips)
SERVICES = [("web", "Website"), ("leads", "Leads & booking"), ("seo", "SEO & analytics"), ("social", "Social & video"),
            ("odoo", "Odoo"), ("ai", "AI chatbot"), ("pitch", "Showcase & decks"), ("brand", "Brand & design")]

# status: live | progress | proposal | concept | paused ; svc values: 2 delivered, 1 proposed or demo
CLIENTS = [
    dict(slug="casa", name="Casa Escondida Anilao", mono="CE", c="#1E4691", ind="Dive resort", where="Anilao, Philippines", cc="PH", status="live",
         site="casa-escondida-anilao", url="https://www.casaescondida-anilao.com/",
         svc=dict(web=2, leads=2, seo=2, social=2, odoo=2, ai=2, pitch=2),
         did=["Resort website rebuilt on its own domain: rooms, diving, location, gallery, a blog and an English/Chinese toggle",
              "A Book Now page with a quotation-request form",
              "GA4, Tag Manager and Search Console, with monthly Search Console reports",
              "A social media library of image posts, video posts and reels for five channels",
              "Marketing showcase and market-research brief; an Odoo proposal microsite",
              "An Odoo ERP rollout, starting with accounting (in progress)"],
         links=[("Live site", "https://www.casaescondida-anilao.com/"), ("Showcase", "https://technextsg.github.io/casa-escondida-marketing-showcase/"),
                ("Odoo proposal", "https://technextmarketing.github.io/casa-escondida-sales-proposal/")]),
    dict(slug="bhd", name="BHD Asia", mono="BH", c="#137A4A", ind="Coaching & HR consulting", where="Singapore", cc="SG", status="live",
         site="bhd-asia", url="https://bhdasia.com/",
         svc=dict(web=2, leads=2, seo=2, social=2, odoo=1, ai=2, pitch=2, brand=2),
         did=["bhdasia.com rebuilt as a fast site on the client's own domain",
              "Team bio pages and an events hub with countdowns for TRE™ workshops in Singapore, Bucharest and online",
              "Lead capture on every form, logged to a sheet and emailed to the client",
              "SEO pass: sitemap, structured data for events and courses, llms.txt",
              "Social scheduling on Facebook and LinkedIn, and webinar clips with burned-in subtitles",
              "A 2026 marketing plan and a brand kit"],
         links=[("Live site", "https://bhdasia.com/")]),
    dict(slug="hb", name="HummingBeing", mono="HB", c="#137A4A", ind="TRE™ & somatic coaching", where="Singapore · worldwide", cc="SG", status="live",
         site="hummingbeing", url="https://hummingbeing.com/",
         svc=dict(web=2, leads=2, seo=2, social=1, odoo=1, ai=2, pitch=2, brand=2),
         did=["hummingbeing.com rebuilt with event pages and an online-session guide",
              "Lead capture on every form, emailed to the client",
              "TRE™ provider certification 2027 pages",
              "An Odoo events webshop demo with tiered tickets and SGD/EUR pricelists",
              "An Odoo implementation proposal and deck"],
         links=[("Live site", "https://hummingbeing.com/")]),
    dict(slug="tresg", name="TRE™ in Singapore", mono="TS", c="#137A4A", ind="TRE™ community", where="Singapore", cc="SG", status="progress",
         site="tre-singapore", url="https://technextmarketing.github.io/tre-singapore/",
         svc=dict(web=2, leads=2, ai=2, pitch=2),
         did=["Community website: events shared with HummingBeing and a facilitator directory with profile pages",
              "Contact and newsletter forms that email the client",
              "A website showcase and promotion-plan deck"],
         links=[("Site", "https://technextmarketing.github.io/tre-singapore/")]),
    dict(slug="trebali", name="TRE Worldwide Conference 2027", mono="TW", c="#137A4A", ind="International conference", where="Bali, Indonesia", cc="ID", status="proposal",
         site="tre-bali-conference", url="https://technextmarketing.github.io/tre-bali-conference/",
         svc=dict(web=2, leads=2, social=1, odoo=1, pitch=2),
         did=["A 17-slide proposal deck with page, countdown and agenda mockups",
              "An event website prototype with a live countdown, ticket ladder and registration",
              "An Odoo CRM lead bridge for registrations",
              "An event marketing showcase with social mockups and AI video"],
         links=[("Event site", "https://technextmarketing.github.io/tre-bali-conference/"), ("Showcase", "https://technextmarketing.github.io/tre-bali-marketing-showcase/")]),
    dict(slug="saymara", name="Saymara B. Ryon", mono="SR", c="#0E7C86", ind="Holistic coaching & TRE®", where="Bucharest, Romania", cc="RO", status="progress",
         site="saymara-website", url="https://technextmarketing.github.io/saymara-website/",
         svc=dict(web=2, seo=2, social=2, ai=2, pitch=2),
         did=["A Romanian-language redesign of the whole site, with an EN/RO toggle and an events page",
              "A marketing showcase with a social-media audit",
              "Atelier de Suflet event pages with a live countdown",
              "Webshop product copy for TRE® events",
              "17 webinar clips with burned-in subtitles, scheduled on Facebook"],
         links=[("Redesign", "https://technextmarketing.github.io/saymara-website/"), ("Showcase", "https://technextmarketing.github.io/saymara-marketing-showcase/")]),
    dict(slug="niv", name="nivellipso®", mono="NV", c="#714B67", ind="Clear aligners & brackets", where="Switzerland", cc="CH", status="live",
         site="nivellipso", url="https://www.nivellipso.com/",
         svc=dict(web=2, seo=2, ai=2, brand=2),
         did=["The production site, maintained by TechNext, with multi-language support",
              "2026 price lists applied across the site, documents and chatbot",
              "Site-wide audit fixes, and the chatbot moved to a serverless endpoint",
              "Webshop imagery changes reviewed on a mockup, then shipped to production",
              "VISIBAL, a patient and clinic app prototype",
              "An SEO, GEO and AEO audit with a monthly analytics report"],
         links=[("Live site", "https://www.nivellipso.com/"), ("VISIBAL prototype", "https://technextsg.github.io/visibal-app/")]),
    dict(slug="hdh", name="HDH AG", mono="HD", c="#714B67", ind="Dental & medical OEM", where="Switzerland", cc="CH", status="progress",
         site="hdh-ag-visibal", url="https://technextsg.github.io/hirsch-dynamics-visibal/",
         svc=dict(web=2, social=2, ai=1, odoo=1, pitch=2),
         did=["A group website concept: four divisions, VISIBAL and podcast pages, in four languages",
              "A social media library: Facebook and Instagram posts and reels",
              "An email-provider decision brief",
              "A four-track plan: an AI ordering assistant, email, Odoo stabilisation and Odoo 20 readiness"],
         links=[("Website concept", "https://technextsg.github.io/hirsch-dynamics-visibal/")]),
    dict(slug="jrt", name="JR-Tech Solution", mono="JR", c="#3167CA", ind="Commercial kitchens", where="Penang, Malaysia", cc="MY", status="progress",
         site="jrtech-website", url="https://technextsg.github.io/jrtech-website/",
         svc=dict(web=2, leads=2, ai=2, odoo=1, pitch=2),
         did=["A website rebuild with the product catalogue, a quote request and a chatbot",
              "A marketing showcase with market research",
              "An Odoo proposal microsite: CRM, Accounting with SST and MyInvois, Field Service, Inventory, POS",
              "A growth-roadmap pitch deck and a quotation builder with shareable links",
              "An Odoo implementation proposal and a SQL Account to Odoo migration brief"],
         links=[("Website", "https://technextsg.github.io/jrtech-website/"), ("Showcase", "https://technextmarketing.github.io/jrtech-marketing-showcase/"),
                ("Odoo proposal", "https://technextmarketing.github.io/jrtech-sales-proposal/JR-Tech/")]),
    dict(slug="imc", name="Immaculate Connections", mono="IC", c="#3167CA", ind="Travel agency", where="Cebu, Philippines", cc="PH", status="progress",
         site="immaculate-connections-redesign", url="https://technextmarketing.github.io/immaculateconnectionsph/",
         svc=dict(web=2, leads=2, seo=2, odoo=1, pitch=2),
         did=["A website redesign with 15 tour packages and an inquiry form that produces a quotation",
              "An audit of the current site and a 26-page marketing proposal",
              "An Odoo Accounting proposal microsite with Philippine BIR and VAT context",
              "An inquiry-to-payment flowchart deck and an implementation proposal",
              "An admin dashboard mockup for packages, departures and transport"],
         links=[("Redesign", "https://technextmarketing.github.io/immaculateconnectionsph/")]),
]

STATUS = {"live": "Live", "progress": "In progress", "proposal": "Proposal", "concept": "Concept", "paused": "Paused"}

# the map: pins for countries with clients (solid) and with proposals only (hollow)
PINS = [
    ("SG", 103.82, 1.35, "Singapore", "BHD Asia · HummingBeing\nTRE™ in Singapore", True, "r"),
    ("PH", 121.0, 13.2, "Philippines", "Casa Escondida\nImmaculate Connections", True, "t"),
    ("MY", 100.33, 5.41, "Malaysia", "JR-Tech Solution", True, "l"),
    ("ID", 115.19, -8.41, "Indonesia", "TRE Worldwide\nConference 2027", True, "b"),
    ("CH", 8.23, 46.8, "Switzerland", "nivellipso® · HDH AG", True, "b"),
    ("RO", 26.1, 44.43, "Romania", "Saymara B. Ryon", True, "r"),
    ("UK", 0.5, 51.2, "United Kingdom", "Proposal", False, "t"),
]
